name: Marceldegraaf.net
pygments: true
exclude: [ Gemfile, Gemfile.lock, deploy.sh, LICENSE, README.md ]
sass:
  syntax: sass        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
